#!/usr/bin/env bash
# Define a function that takes a domain and a subdomain as arguments and prints the output
get_subdomain_info() {
    dig +short $2.$1 | awk -v domain=$1 -v subdomain=$2 'NR==1 {type="A"; dest=$1} NR==2 {type="CNAME"; dest=$2} END {printf "The subdomain %s.%s is a %s record and points to %s\n", subdomain, domain, type, dest}'
}
if [ -z "$1" ]; then
echo "Usage: $0 domain [subdomain]"
exit 1
fi
if [ -z "$2" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info $1 $sub
        done
    else
        get_subdomain_info $1 $2
fi
