#!/usr/bin/env bash
# Function to fetch and display DNS record
fetch_dns_record() {
    local domain=$1
    local subdomain=$2
    local dns_record=$(dig +short $subdomain.$domain)
    if [[ -z "$dns_record" ]]; then
        echo "The subdomain $subdomain does not exist."
    else
        local record_type=$(echo $dns_record | awk '{print $4}')

        echo "The subdomain $subdomain is a $record_type record and points to $dns_record"
    fi
}

if [[ -z "$1" ]]; then
    echo "Error: Domain name is required."
    exit 1
fi

domain=$1

declare -a subdomains=("www" "lb-01" "web-01" "web-02")

if [[ -n "$2" ]]; then
    fetch_dns_record $domain $2
else
    for subdomain in "${subdomains[@]}"; do
        fetch_dns_record $domain $subdomain
    done
fi
