#!/bin/bash

# Update packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Start nginx
sudo service nginx start
echo "Hello World" | sudo tee /var/www/html/index
# Create a configuration file for the redirection
echo 'server {
    listen 80;
    server_name localhost;

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
}' | sudo tee /etc/nginx/sites-available/redirection

# Enable the configuration by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/

# Remove the default configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart nginx to apply the changes
sudo service nginx restart

