#!/usr/bin/env bash
# script that Configure Nginx server so that /redirect_me
# is redirecting to another page and /xyzfoo returns a custom 404 page.
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

echo "server {
        listen 80;
        server_name my_server;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
}" | sudo tee /etc/nginx/sites-available/redirection
if [ -L /etc/nginx/sites-enabled/redirection ]; then
    sudo rm /etc/nginx/sites-enabled/redirection
fi
sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/
if [ -f /etc/nginx/sites-enabled/default ]; then
    sudo rm /etc/nginx/sites-enabled/default
fi
sudo service nginx reload
