#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get install -y haproxy
sudo systemctl enable haproxy

echo '
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server web-01 100.26.173.131:80 check
   server web-02 18.206.202.74:80 check
' | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart

