#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ | sudo tee /var/run/myscript.pid > /dev/null
T_handler(){
    echo "I hate the kill command"
    sudo rm -f /var/run/myscript.pid
}
I_handler(){
    echo "Y U no love me?!"
}
trap "T_handler" SIGTERM
trap "I_handler" SIGINT
while true
do
echo "To infinity and beyond"
sleep 2
done
