#!/usr/bin/env bash
#  Manage my process
case "$1" in
start)
sudo ./manage_my_process &
echo $! | sudo tee /var/run/my_process.pid > /dev/null
echo "manage_my_process started"
;;
stop)
PID=$(cat /var/run/my_process.pid)
sudo kill -SIGTERM $PID
sudo rm -f /var/run/my_process.pid
echo "manage_my_process stopped"
;;
restart)
sudo./manage_my_process &
echo $! | sudo tee /var/run/my_process.pid > /dev/null
echo "manage_my_process restarted"
;;
*)
echo "Usage: manage_my_process {start|stop|restart}"
;;
esac