#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd
# Read /etc/passwd file
while IFS=: read -r username userid _ _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd


