#!/usr/bin/env bash
#cript that displays Best School 10 times
#for the 9th iteration, displays Best School
#then Hi on a new line.
count=0
while [ $count -lt 10 ]
do
if [ $count -eq 8 ]
then
echo "Hi"
else
echo "Best School"
fi
count=$((count+1))
done
